feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true

hystrix.command:
  fallbackClient_getPostsWithPathAndQuery:
    circuitBreaker:
      requestVolumeThreshold: 1
      sleepWindowInMilliseconds: 10000
      errorThresholdPercentage: 50
      metrics.rollingStats.timeInMilliseconds: 3000
    execution.isolation.thread.timeoutInMilliseconds: 100000

resilience4j:
  circuitbreaker:
    instances:
      fallbackClient_getPostsWithPathAndQuery:
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 1
        ignoreExceptions:
          - feign.FeignException.FeignClientException
  timelimiter:
    instances:
      fallbackClient_getPostsWithPathAndQuery:
        timeoutDuration: 10s
        cancelRunningFuture: true
  bulkhead:
    instances:
      fallbackClient_getPostsWithPathAndQuery:
        maxConcurrentCalls: 25

---
spring:
  profiles: dev
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: hotire
    listener:
      ack-mode: manual
  cloud.config.uri: http://localhost:8888

test:
  topic: embedded-test-topic




