feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true

hystrix.command:
  fallbackClient_getPostsWithPathAndQuery:
    circuitBreaker:
      requestVolumeThreshold: 1
      sleepWindowInMilliseconds: 10000
      errorThresholdPercentage: 50
      metrics.rollingStats.timeInMilliseconds: 3000
    execution.isolation.thread.timeoutInMilliseconds: 100000


---
spring:
  profiles: dev
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: hotire
    listener:
      ack-mode: manual
  cloud.config.uri: http://localhost:8888

test:
  topic: embedded-test-topic




