resilience4j:
  circuitbreaker:
    instances:
      hello:
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 30
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 20
        registerHealthIndicator: false
        minimumNumberOfCalls: 1
